server:
  port: 5555

spring:
  datasource:
#    url: 'jdbc:mysql://localhost:3306/fhir_khxy'
#    username: khxy
#    password: khxy
#    driverClassName: com.mysql.jdbc.Driver


    url: 'jdbc:h2:file:./target/database/khxy'
    #url: jdbc:h2:mem:test_mem
    username: sa
    password: null
    driverClassName: org.h2.Driver
    max-active: 15
  jpa:
    properties:
#      hibernate.dialect: org.hibernate.dialect.h2dialect
#      hibernate.search.model_mapping: ca.uhn.fhir.jpa.search.lucenesearchmappingfactory
      hibernate.format_sql: false
      hibernate.show_sql: false
      hibernate.hbm2ddl.auto: update
      hibernate.jdbc.batch_size: 20
#      hibernate.cache.use_query_cache: false
#      hibernate.cache.use_second_level_cache: false
#      hibernate.cache.use_structured_entries: false
#      hibernate.cache.use_minimal_puts: false
#      hibernate.search.default.directory_provider: filesystem
#      hibernate.search.default.indexbase: target/lucenefiles
#      hibernate.search.lucene_version: lucene_current

  batch:
    job:
      enabled: false

hapi:
  fhir:
    use_authentication: true


    fhir_version: R4
    allow_external_references: true
    allow_cascading_deletes: true
    default_encoding: JSON
    default_pretty_print: true
    fhirpath_interceptor_enabled: true

    ### enable to set the Server URL
    # server_address: http://localhost:5555/baseR4
    ### This is the FHIR version. Choose between, DSTU2, DSTU3, R4 or R5
#    defer_indexing_for_codesystems_of_size: 101
    #implementationguides:
      #example from registry (packages.fhir.org)
      #swiss:
        #name: swiss.mednet.fhir
        #version: 0.8.0
      #example not from registry
      #ips_1_0_0:
        #url: https://build.fhir.org/ig/HL7/fhir-ips/package.tgz
        #name: hl7.fhir.uv.ips
        #version: 1.0.0

    #supported_resource_types:
    #  - Patient
    #  - Observation
#    allow_contains_searches: true
#    allow_multiple_delete: true
#    allow_override_default_search_params: true
#    allow_placeholder_references: true
#    auto_create_placeholder_reference_targets: false
#    default_page_size: 20
#    enable_index_missing_fields: false
#    enforce_referential_integrity_on_delete: false
#    enforce_referential_integrity_on_write: false
#    etag_support_enabled: true
#    expunge_enabled: true
#    daoconfig_client_id_strategy: null
#    filter_search_enabled: true
#    graphql_enabled: true
#    narrative_enabled: true
    #partitioning:
    #  cross_partition_reference_mode: true
    #  multitenancy_enabled: true
    #  partitioning_include_in_search_hashes: true
    #cors:
    #  allow_Credentials: true
      # Supports multiple, comma separated allowed origin entries
      # cors.allowed_origin=http://localhost:8080,https://localhost:8080,https://fhirtest.uhn.ca
    #  allowed_origin:
    #    - '*'

#    logger:
#      error_format: 'ERROR - ${requestVerb} ${requestUrl}'
#      format: >-
#        Path[${servletPath}] Source[${requestHeader.x-forwarded-for}]
#        Operation[${operationType} ${operationName} ${idOrResourceName}]
#        UA[${requestHeader.user-agent}] Params[${requestParameters}]
#        ResponseEncoding[${responseEncodingNoDefault}]
#      log_exceptions: true
#      name: fhirtest.access
#    max_binary_size: 104857600
#    max_page_size: 200
#    retain_cached_searches_mins: 60
#    reuse_cached_search_results_millis: 60000
    tester:
        home:
          name: Local Tester
          server_address: 'http://localhost:5555/fhir'
          refuse_to_fetch_third_party_urls: false
          fhir_version: R4

        global:
          name: Global Tester
          server_address: "http://hapi.fhir.org/baseR4"
          refuse_to_fetch_third_party_urls: false
          fhir_version: R4
    validation:
      requests_enabled: true
      responses_enabled: true
#    binary_storage_enabled: true
#    bulk_export_enabled: true
#    partitioning_multitenancy_enabled:
#    subscription:
#      resthook_enabled: false
#      websocket_enabled: false
#      email:
#        from: some@test.com
#        host: google.com
#        port:
#        username:
#        password:
#        auth:
#        startTlsEnable:
#        startTlsRequired:
#        quitWait:
#    lastn_enabled: true
